settings:
  minecraft-tag: 'minecraft'
  cancelled-tag: 'cancelled'
  console-tag: 'console'
  command-prefix: '.'
  debug: false
  console-commands: ['reload', 'save-all']
  hold-after-enable: {chat: 0, joins: 0, quits: 0, kicks: 0, bans: 0}
  #bind-address: 127.0.0.1
  formatting:
    ####     VARIABLES AND COLORS: %name% (as in %message% or %yellow%)
    ####     How are we going to handle this now: %prefix% %suffix% %modPredix% %modSuffix%
    ####     IRC FORMATTING: %b% %u% %r% %o% %k% %kNUM% (NUM is 0 to 15); Do the same as CTRL+key in mIRC (%o% uses'foreground')
    from-game:
      chat: '(%sender%) %message%'
      private: '(%sender%) %message%'
      action: '* %sender% %message%'
      join: '[%sender% connected]'
      quit: '[%sender% disconnected]'
      kick: '[%moderator% KICKED %sender% (%message%)]'
      admin: '%sender% to online admins ->- %message%'
      generic: '%message%'
    from-irc:
      chat: '[%srcChannel%] <%sender%> %message%'
      private: '%sender% whispers> %message%'
      action: '[%srcChannel%] * %sender% %message%'
      join: '[%srcChannel%] * Joins: %sender%'
      part: '[%srcChannel%] * Parts: %sender%'
      quit: '[%srcChannel%] * Quits: %sender% (%message%)'
      kick: '[%srcChannel%] * %sender% was kicked by %moderator% (%message%)'
      nick: '[%srcChannel%] * %sender% is now known as %message%'
     
bots:
  - nickname: 'CraftIRCbot'
    server: 'irc.esper.net'
    port: 6667
    userident: 'bot'
    serverpass: ''  #This isn't the nickserv password
    ssl: false
    message-delay: 1000
    admin-prefixes: ['@', '%']
    ignored-users: []
    auth:
      method: 'nickserv' #Available methods: 'none', 'nickserv', 'gamesurge', 'quakenet'
      username: ''
      password: ''
    on-connect:
    # - 'PRIVMSG MyBoss :I live again!'
    channels:
      - name: '#changeme'
        password: ''
        tag: 'changeme'
        on-join:
        # - 'PRIVMSG #changeme :Howdy do!'
        
paths:
  - source: 'minecraft'
    target: 'changeme'
  - source 'changeme'
    target: 'minecraft'
    filters:
      #Each filter is a disjunction with message fields and regular expressions they must match for the message to be filtered.
      - message: '^\.[^ ]+'
    formatting:
      #chat: '[%srcChannel%] <%sender%> %message%'
      #join: '[%srcChannel%] * Joins: %sender%'

default-attributes:
	disable: false
	attributes:
		admin: false
		colors: true
		chat: true
		action: true
		join: true
		part: true
		nick: true
		quit: true
		kick: true
		private: true
		command: true
		say: true
		generic: true

colormap:
  - {irc: 0, game: '§0', name: 'background'}
  - {irc: 2, game: '§1', name: 'navy'}
  - {irc: 3, game: '§2', name: 'darkgreen'}
  - {irc: 10, game: '§3', name: 'teal'}
  - {irc: 5, game: '§4', name: 'maroon'}
  - {irc: 6, game: '§5', name: 'purple'}
  - {irc: 7, game: '§6', name: 'orange'}
  - {irc: 15, game: '§7', name: 'grey'}
  - {irc: 14, game: '§8', name: 'darkgrey'}
  - {irc: 12, game: '§9', name: 'blue'}
  - {irc: 9, game: '§a', name: 'green'}
  - {irc: 11, game: '§b', name: 'cyan'}
  - {irc: 4, game: '§c', name: 'red'}
  - {irc: 13, game: '§d', name: 'magenta'}
  - {irc: 8, game: '§e', name: 'yellow'}
  - {irc: 1, game: '§f', name: 'foreground'}
