name: CraftIRC
main: com.ensifera.animosity.craftirc.CraftIRC
version: 3.0 ALPHA
commands:
  irc:
    description: Sends a message to all IRC channels
    usage: /<command> [msg]
  to:
    description: Send message to tag
    usage: /<command> [tag] [msg]
  touser:
    description: PM a user
    usage: /<command> [tag] [player] [msg]
  users:
    description: Lists online users
    usage: /<command> [tag]
  admins!:
    description: Sends a notice to admins on IRC
    usage: /<command> [msg]
  ircraw:
    description: Sends a raw line to IRC
    usage: /<command> [botid] [rawirc]
